name: Build-Project
run-name: Build-Project
on: 
  # make sure to remove Push after done testing -PH
  push:
  pull_request:
    branches: [ master, develop, main ]
    types: [ opened ]
jobs:
  Build-Project:
    uses: pchachicho/renci-github-actions/.github/workflows/build-project-tycho.yml@main
    secrets: inherit