name: flake8

on:
  push:
    # paths-ignore:
    #   - README.md
    #   - .old_cicd/*
    #   - .github/*
    #   - .github/workflows/*
    #   - LICENSE
    #   - .gitignore
    #   - .dockerignore
    #   - .githooks
  # Run flake every time.
  pull_request:
    branches: [ master, develop, main ]
    types: [ opened ]

jobs:
  Code-Checks:
    uses: pchachicho/renci-github-actions/.github/workflows/code-checks-tycho.yml@main
    secrets: inherit