name: upload-pypi
run-name: Package and Upload to Pypi  
on:
  push:
    # branches:
    #   - master
    #   - main
    # paths-ignore:
    #   - README.md
    #   - .old_cicd/*
    #   - .github/*
    #   - .github/workflows/*
    #   - LICENSE
    #   - .gitignore
    #   - .dockerignore
    #   - .githooks
    # tags:
    #   - 'v[0-9]+.[0-9]+.*'
jobs:
  Upload-Pypi:
    uses: pchachicho/renci-github-actions/.github/workflows/pypi-upload.yml@main
    secrets: inherit