# This workflow will create an image for any tycho development taking place, not in master branch.
# We use the {{ github.ref_name }} ie branch name and date to ensure uniqueness of the package.
name: upload-dev-pypi
run-name: Package and Upload develop image to Pypi  
on:
  push:
    # branches-ignore:
    #   - master
    #   - main
    # paths-ignore:
    #   - README.md
    #   - .old_cicd/*
    #   - .github/*
    #   - .github/workflows/*
    #   - LICENSE
    #   - .gitignore
    #   - .dockerignore
    #   - .githooks
jobs:
  Upload-Dev-Pypi:
    uses: pchachicho/renci-github-actions/.github/workflows/pypi-dev-upload.yml@main
    secrets: inherit