name: trivy-pr-scan 
on:
  # make sure to remove Push after testing is complete - PH
  push:
  pull_request:
    branches:
      - develop
      - master
      - main 
    # types: [ opened, synchronize ]
    # paths-ignore:
    # - README.md
    # - .old_cicd/*
    # - .github/*
    # - .github/workflows/*
    # - LICENSE
    # - .gitignore
    # - .dockerignore
    # - .githooks

jobs:
  trivy-pr-scan:
    uses: pchachicho/renci-github-actions/.github/workflows/trivy-pr-scan-tycho.yml@main
    secrets: inherit